# Generated by Django 2.2.3 on 2020-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('href', models.CharField(max_length=150, verbose_name='播放地址')),
                ('imgsrc', models.CharField(max_length=150, verbose_name='图片链接')),
                ('author', models.CharField(max_length=60, verbose_name='导演')),
                ('pers', models.CharField(max_length=255, verbose_name='主演')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('year', models.CharField(max_length=10, verbose_name='年份')),
                ('mes', models.CharField(max_length=2000, verbose_name='简介')),
            ],
            options={
                'verbose_name': '动漫',
                'verbose_name_plural': '动漫',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('href', models.CharField(max_length=150, verbose_name='播放地址')),
                ('imgsrc', models.CharField(max_length=150, verbose_name='图片链接')),
                ('author', models.CharField(max_length=60, verbose_name='导演')),
                ('pers', models.CharField(max_length=255, verbose_name='主演')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('year', models.CharField(max_length=10, verbose_name='年份')),
                ('mes', models.CharField(max_length=2000, verbose_name='简介')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='Sitcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('href', models.CharField(max_length=150, verbose_name='播放地址')),
                ('imgsrc', models.CharField(max_length=150, verbose_name='图片链接')),
                ('author', models.CharField(max_length=60, verbose_name='导演')),
                ('pers', models.CharField(max_length=255, verbose_name='主演')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('year', models.CharField(max_length=10, verbose_name='年份')),
                ('mes', models.CharField(max_length=2000, verbose_name='简介')),
            ],
            options={
                'verbose_name': '连续剧',
                'verbose_name_plural': '连续剧',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('href', models.CharField(max_length=150, verbose_name='播放地址')),
                ('imgsrc', models.CharField(max_length=150, verbose_name='图片链接')),
                ('author', models.CharField(max_length=60, verbose_name='导演')),
                ('pers', models.CharField(max_length=255, verbose_name='主演')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('year', models.CharField(max_length=10, verbose_name='年份')),
                ('mes', models.CharField(max_length=2000, verbose_name='简介')),
            ],
            options={
                'verbose_name': '综艺',
                'verbose_name_plural': '综艺',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
    ]
