# Generated by Django 2.2.3 on 2019-12-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daikuan',
            fields=[
                ('id', models.CharField(default='DD', help_text='DD不要删，直接后面加数字', max_length=20, primary_key=True, serialize=False, verbose_name='编码号')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '贷款信息',
                'verbose_name_plural': '贷款信息',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='学号')),
                ('password', models.CharField(default='jianghuai', max_length=32, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, help_text='可不填', max_length=254, verbose_name='注册邮箱')),
                ('phone_number', models.CharField(blank=True, max_length=14, verbose_name='电话号码')),
            ],
            options={
                'verbose_name': '账号管理',
                'verbose_name_plural': '账号管理',
            },
        ),
        migrations.CreateModel(
            name='Stuinfo',
            fields=[
                ('StuNum', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('StuName', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('W', '女'), ('M', '男')], max_length=2, verbose_name='性别')),
                ('department', models.CharField(choices=[('L', '理工部'), ('W', '文艺部'), ('G', '管理部'), ('J', '经济系')], max_length=20, verbose_name='系别')),
                ('stuid', models.CharField(max_length=18, verbose_name='身份证')),
                ('Tel', models.CharField(max_length=12, verbose_name='电话')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('email', models.EmailField(blank=True, help_text='可不填', max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeaNum', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='职工号')),
                ('TeaName', models.CharField(max_length=20, verbose_name='姓名')),
                ('Tel', models.CharField(max_length=12, verbose_name='电话')),
                ('sex', models.CharField(choices=[('W', '女'), ('M', '男')], max_length=2, verbose_name='性别')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.CreateModel(
            name='huankuan',
            fields=[
                ('num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.daikuan', verbose_name='编码号')),
                ('status', models.CharField(choices=[('Y', '是'), ('N', '否')], max_length=2, verbose_name='是否还款')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='还款时间')),
                ('money', models.IntegerField(default=10000, verbose_name='需要还款')),
            ],
            options={
                'verbose_name': '还款信息',
                'verbose_name_plural': '还款信息',
            },
        ),
        migrations.CreateModel(
            name='Shenq2',
            fields=[
                ('stuinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app.Stuinfo')),
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='预编码号')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='申请时间')),
                ('edu', models.IntegerField(default=10000, verbose_name='贷款额度')),
            ],
            options={
                'verbose_name': '贷款申请信息2',
                'verbose_name_plural': '贷款申请信息2',
            },
            bases=('app.stuinfo',),
        ),
        migrations.CreateModel(
            name='shenq',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='预编码号')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='申请时间')),
                ('edu', models.IntegerField(default=10000, verbose_name='贷款额度')),
                ('Stunum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Stuinfo', verbose_name='学号')),
            ],
            options={
                'verbose_name': '贷款申请信息',
                'verbose_name_plural': '贷款申请信息',
            },
        ),
        migrations.AddField(
            model_name='daikuan',
            name='TeaNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher', verbose_name='职工号'),
        ),
        migrations.AddField(
            model_name='daikuan',
            name='num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.shenq', verbose_name='预编码号'),
        ),
    ]
