# Generated by Django 2.2.3 on 2020-01-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191214_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huankuan',
            name='status',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=2, verbose_name='是否还款'),
        ),
    ]
