# Generated by Django 2.2.3 on 2020-01-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200121_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='shenq',
            name='status',
            field=models.IntegerField(default=0, verbose_name='审批状态'),
        ),
    ]
