# Generated by Django 2.2.3 on 2020-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shenq_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shenq2',
            name='stuinfo_ptr',
        ),
        migrations.AddField(
            model_name='daikuan',
            name='status',
            field=models.IntegerField(default=0, verbose_name='还款状态'),
        ),
        migrations.DeleteModel(
            name='huankuan',
        ),
        migrations.DeleteModel(
            name='Shenq2',
        ),
    ]
