# Generated by Django 2.2.3 on 2020-01-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200130_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shenq',
            name='Stunum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stuinfo', verbose_name='学号'),
        ),
    ]
